[package]
name = "hamlib-client"
version = "0.1.0"
edition = "2021"

[dependencies]
adif4rs = { path = "../adif4rs" }
lazy_static = "1.5.0"
log = "0.4.22"
regex = "1.10.6"
time = "0.3.36"
tokio = { version = "1.39.3", features = ["full"] }
