name: "Builds - MacOS"
on:
  push:
    branches:
      - "!main"
      - "*"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
          - target: x86_64-apple-darwin
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Adds rust target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target=${{ matrix.target }}
