name: "Builds - Windows"
on:
  push:
    branches:
      - "!main"
      - "*"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
          - target: aarch64-pc-windows-msvc
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Adds rust target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target=${{ matrix.target }}
